apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-from-jenkins
  labels:
    commit: ${GIT_COMMIT}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-from-jenkins
  template:
    metadata:
      labels:
        app: nginx-from-jenkins
        commit: ${GIT_COMMIT}
        color: blue
    spec:
      containers:
      - name: nginx-from-jenkins
        image: ${DOCKER_REGISTRY}/${DOCKER_REPO}:${GIT_COMMIT}
        imagePullPolicy: Always
        ports:
        - name: nginx-from-jenkins
          containerPort: 80
          protocol: TCP
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-from-jenkins
  labels:
    app: nginx-from-jenkins
    commit: ${GIT_COMMIT}
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: nginx-from-jenkins
    color: blue
  type: LoadBalancer
---
